name       : python-pydrive2
version    : 1.10.1
release    : 1
source     :
    - https://files.pythonhosted.org/packages/cf/cd/1be6f5b4f023331b3f2f519cb3452f64cea7307bdfc76641612a3c02c7ea/PyDrive2-1.10.1.tar.gz : ac29d6da1eff3e5f14d3da0af10ff0bf3d12448427ee4e99d2f8336663455483
license    : Apache-2.0
component  : programming.python
summary    : Google Drive API Python wrapper library
description: |
    PyDrive2 is a wrapper library of google-api-python-client that simplifies many common Google Drive API V2 tasks.
rundeps    :
    - google-api-python-client
    - python-oauth2client
    - python-six
    - python-openssl
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
