name       : python-pydrive2
version    : 1.15.0
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/P/PyDrive2/PyDrive2-1.15.0.tar.gz : 3ae06b66bf963f43524989c87f4d678039441fe059993c6703fb33cc3c6d8aec
homepage   : https://github.com/iterative/PyDrive2
license    : Apache-2.0
component  : programming.python
summary    : Google Drive API Python wrapper library
description: |
    PyDrive2 is a wrapper library of google-api-python-client that simplifies many common Google Drive API V2 tasks.
builddeps  :
    - python-setuptools-scm
rundeps    :
    - google-api-python-client
    - python-oauth2client
    - python-six
    - python-openssl
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
